site_name: 深度学习工程师生存指南
site_description: 深度学习工程师生存指南
site_author: 杨培文
copyright: 杨培文
site_url: https://dl.ypw.io
repo_url: https://github.com/ypwhs/dl-engineer-guidebook
repo_name: ypwhs/dl-engineer-guidebook
edit_uri: edit/master/docs
remote_name: https://github.com/ypwhs/dl-engineer-guidebook
remote_branch: site
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    #    - header.autohide
    #    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  #    - toc.integrate
  language: 'zh'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 打开深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: 关闭深色模式
extra:
  search:
  analytics:
    provider: google
    property: 'UA-111276663-2'
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ypwhs'
    - icon: 'fontawesome/brands/zhihu'
      link: 'https://www.zhihu.com/people/yangpw'
    - icon: 'fontawesome/solid/blog'
      link: 'https://ypw.io'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/ypwhs/'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.critic
  - codehilite
  - toc:
      permalink: false
plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: true
  - git-committers:
      repository: ypwhs/dl-engineer-guidebook
      branch: master
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js
  - js/tablesort.js
nav:
  - 首页:
    - 首页: README.md
    - 如何配置一台深度学习工作站?: how-to-build-deep-learning-workstation.md
    - Windows、Ubuntu 还是 macOS？: windows-linux-or-macos.md
    - Mac 对比: mac-compare.md
    - macOS 软件: macos-software.md
    - macOS 环境: macos-environment.md
    - Python 环境: python-environment.md
    - Ubuntu 装机步骤: ubuntu-install-guide.md
    - Ubuntu 环境: ubuntu-environment.md
    - 常用 Linux 命令: linux-command.md
    - 如何使用 TensorBoard: how-to-use-tensorboard.md
    - CV 学习资源: cv-resources.md
    - 常用 CV 数据集: cv-dataset.md
    - 在 ImageNet 上表现出色的经典模型: best-models-on-imagenet.md
    - 检测模型: detection-models.md
  - 硬件:
    - 如何配置一台深度学习工作站?: how-to-build-deep-learning-workstation.md
    - Windows、Ubuntu 还是 macOS？: windows-linux-or-macos.md
    - 涡轮卡的使用技巧-风扇调速: turbo-fan-control.md
  - Mac:
    - Mac 对比: mac-compare.md
    - macOS 软件: macos-software.md
    - macOS 环境: macos-environment.md
    - Python 环境: python-environment.md
    - 常用 Linux 命令: linux-command.md
  - Linux:
    - Ubuntu 装机步骤: ubuntu-install-guide.md
    - Ubuntu 环境: ubuntu-environment.md
    - Python 环境: python-environment.md
    - 常用 Linux 命令: linux-command.md
  - CV:
    - CV 学习资源: cv-resources.md
    - 常用 CV 数据集: cv-dataset.md
    - 在 ImageNet 上表现出色的经典模型: best-models-on-imagenet.md
    - 检测模型: detection-models.md
  - 常识:
    - Windows、Ubuntu 还是 macOS？: windows-linux-or-macos.md
    - 为什么我们要用 Python 语言: why-use-python.md
  - 使用技巧:
    - 如何使用 TensorBoard: how-to-use-tensorboard.md
    - 如何使用 PyCharm 远程调试: remote-debugging-with-pycharm.md
    - Docker 是个好东西: docker-is-good.md
    - Windows 离线 Python 环境: offline-python-environment.md
    - 如何可视化 PyTorch 模型: visualize-pytorch-model.md
  - 关于本站:
    - 如何优雅地写文章: how-to-write-article-gracefully.md
