site_name: 深度学习工程师生存指南
site_description: 深度学习工程师生存指南
site_author: 杨培文
copyright: 杨培文
site_url: https://dl.ypw.io
repo_url: https://github.com/ypwhs/dl-engineer-guidebook
repo_name: ypwhs/dl-engineer-guidebook
remote_name: git@github.com:ypwhs/dl-engineer-guidebook.git
remote_branch: site
edit_uri: blob/mkdocs/docs
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'light green'
    accent: 'light green'
  feature:
    tabs: true
google_analytics:
  - 'UA-111276663-2'
  - 'auto'
extra:
  search:
  social:
    - type: 'github'
      link: 'https://github.com/ypwhs'
    - type: 'book'
      link: 'https://www.zhihu.com/people/yangpw'
    - type: 'globe'
      link: 'https://ypw.io'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/ypwhs/'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.critic
  - toc:
      permalink: false
nav:
  - 首页: README.md
  - 如何配置一台深度学习工作站?: how-to-build-deep-learning-workstation.md
  - Windows、Ubuntu 还是 macOS？: windows-linux-or-macos.md
  - Mac 对比: mac-compare.md
  - macOS 软件: macos-software.md
  - macOS 环境: macos-environment.md
  - Python 环境: python-environment.md
  - Ubuntu 装机步骤: ubuntu-install-guide.md
  - Ubuntu 环境: ubuntu-environment.md
  - 常用 Linux 命令: linux-command.md
  - CV 学习资源: cv-resources.md
  - 常用 CV 数据集: cv-dataset.md
  - 在 ImageNet 上表现出色的经典模型: best-models-on-imagenet.md
  - 如何使用 TensorBoard: how-to-use-tensorboard.md
  - 硬件:
    - 如何配置一台深度学习工作站?: how-to-build-deep-learning-workstation.md
    - Windows、Ubuntu 还是 macOS？: windows-linux-or-macos.md
  - Mac:
    - Mac 对比: mac-compare.md
    - macOS 软件: macos-software.md
    - macOS 环境: macos-environment.md
    - Python 环境: python-environment.md
  - Linux:
    - Ubuntu 装机步骤: ubuntu-install-guide.md
    - Ubuntu 环境: ubuntu-environment.md
    - Python 环境: python-environment.md
    - 常用 Linux 命令: linux-command.md
  - CV:
    - CV 学习资源: cv-resources.md
    - 常用 CV 数据集: cv-dataset.md
    - 在 ImageNet 上表现出色的经典模型: best-models-on-imagenet.md
  - 使用技巧:
    - 如何使用 TensorBoard: how-to-use-tensorboard.md
    - 如何使用 PyCharm 远程调试: remote-debugging-with-pycharm.md
    - Docker 是个好东西: docker-is-good.md